Introduce workflow to update documentation
xtermjs/xtermjs.org pull request #173
Opened 2022-04-02 12:05 UTC by silamon

Fixes https://github.com/xtermjs/xterm.js/issues/2606

When needed, the workflow can be triggered under Github Actions. It will update the docs and open a Pull Request.

2022-12-02 20:49 UTC, Tyriar requested changes
Very cool if this works 🙂

2022-12-02 20:49 UTC, Tyriar commented on .github/workflows/update-docs.yml
> +        uses: peter-evans/create-pull-request@v4
Can you pin these actions to commits instead of branches so I can review the code?

2022-12-19 18:54 UTC, silamon commented on .github/workflows/update-docs.yml
> +        uses: peter-evans/create-pull-request@v4
Still works: https://github.com/silamon/xtermjs.org/pull/4
I will pin them to the latest released tag with commit sha.

2023-09-16 09:26 UTC, silamon commented
@Tyriar , updated everything today and it still works. If you don't want to merge this one, can you close it? I've also opened a PR to update the documentation to xterm 5.3.0 using this github action workflow that you can merge if you don't want to merge this one.

2023-09-16 14:41 UTC, Tyriar approved these changes
Thanks for the ping, totally forgot about this 😅 

Will merge as see how it goes 🤞

2023-09-16 14:41 UTC, merged

2023-09-16 14:42 UTC, Tyriar commented
First run https://github.com/xtermjs/xtermjs.org/actions/runs/6207984904

2023-09-16 14:43 UTC, Tyriar commented
Extremely cool! Thanks for fixing this pretty big problem 👏 https://github.com/xtermjs/xtermjs.org/pull/191